#include <stdlib.h>
#include <iostream>
#include <iomanip>
#include <math.h>
#include <stddef.h>
#include <string>
#include <time.h>
#include <ctime>
#include <chrono>
#include <fstream>
#include "utilities/file.h"
#include "utilities/chrono.h"
#include "structures/arreglo.h"
#include "structures/avl.h"
#include "structures/lista.h"
#include "structures/hash.h"
#include "utilities/generar.h"
